# Generated by Django 5.1.3 on 2024-12-26 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiton', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=64, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('READY', '결제준비'), ('IN_PROGRESS', '결제중'), ('DONE', '결제완료'), ('CANCELED', '결제취소'), ('FAILED', '결제실패')], default='READY', max_length=12)),
                ('payment_key', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('membership', '회원권'), ('classticket', '수업권')], max_length=20)),
                ('item_id', models.IntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiton.member')),
            ],
        ),
    ]
