# Generated by Django 5.1.3 on 2024-12-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiton', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='편의 시설')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', '수강생'), ('instructor', '강사'), ('centerowner', '센터장')], max_length=20, verbose_name='역할'),
        ),
        migrations.AddField(
            model_name='center',
            name='amenity',
            field=models.ManyToManyField(to='fiton.amenity', verbose_name='편의시설'),
        ),
    ]
