# Generated by Django 5.1.3 on 2024-12-24 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiton', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='수업 종류')),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('reserved', '예약됨'), ('Waiting for the reservation', '예약대기중'), ('reservation canceled', '예약취소'), ('Reservation Completed', '예약 종료'), ('Class Completed', '수업 종료')], default='reserved', max_length=50, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='fiton.class_type', verbose_name='수업 종류'),
        ),
    ]
