# Generated by Django 5.1.3 on 2024-12-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiton', '0002_amenity_alter_user_role_center_amenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='center_images/', verbose_name='센터 이미지'),
        ),
    ]
