# Generated by Django 5.1.3 on 2024-12-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiton', '0002_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('reserved', '예약됨'), ('Waiting for the reservation', '예약대기중'), ('reservation canceled', '예약취소'), ('class start', '수업시작')], default='reserved', max_length=50, verbose_name='상태'),
        ),
    ]
