# Generated by Django 5.1.3 on 2024-12-24 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiton', '0002_class_type_alter_reservation_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classticket',
            name='class_name',
        ),
        migrations.AddField(
            model_name='classticket',
            name='class_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='class_ticket', to='fiton.class_type', verbose_name='수업 종류'),
            preserve_default=False,
        ),
    ]
