# Generated by Django 5.1.3 on 2024-12-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiton', '0002_add_item_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='classticketowner',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='사용한 수업권 횟수'),
        ),
        migrations.AlterField(
            model_name='classticketowner',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='수업권 개수'),
        ),
    ]
