# Generated by Django 5.1.3 on 2024-12-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiton', '0003_remove_classticket_class_name_classticket_class_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='평균 별점'),
        ),
    ]
