# Generated by Django 5.1.3 on 2024-12-28 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiton', '0004_class_exercises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='exercises',
        ),
        migrations.AddField(
            model_name='class',
            name='exercises',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='fiton.exercise', verbose_name='운동 종목'),
        ),
    ]
