# Generated by Django 5.1.3 on 2024-12-28 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiton', '0005_remove_class_exercises_class_exercises'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='exercises',
            new_name='exercise',
        ),
    ]
