# Generated by Django 5.1.3 on 2024-12-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiton', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('reserved', '예약됨'), ('Waiting for the reservation', '예약대기중'), ('reservation canceled', '예약취소'), ('Reservation Completed', '예약 종료'), ('Class Completed', '수업 종료'), ('class canceled', '수업 취소'), ('class start', '수업 시작')], default='reserved', max_length=50, verbose_name='상태'),
        ),
    ]
